name: PR

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Linting commit message
        uses: wagoid/commitlint-github-action@b948419dd99f3fd78a6548d48f94e3df7f6bf3ed # v6.2.1

      - name: Setup Node
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: 24

      - name: Linting commit
        run: |
          npm i -g conventional-changelog-conventionalcommits
          npm i -g commitlint@latest
          npm i -g @commitlint/config-conventional
          echo "module.exports = {extends: ['@commitlint/config-conventional']};" > commitlint.config.js
          echo "$PR_TITLE" | npx commitlint --verbose
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}

      - name: Labeling
        uses: actions/labeler@bf12e9b00b37c5c0ca2b87b79b2daf7891dbda13 # v7.0.0
        # disable until figuring out a way to do this without pull_request_target
        if: false
